name: TMP
on: workflow_dispatch

permissions:
  contents: read
  packages: write

jobs:
  manifest:
    timeout-minutes: 10
    runs-on: ubuntu-24.04
    name: merge images
    steps:
    - uses: docker/login-action@v3
      name: login to ghcr.io
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}        
    - name: get metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository }}:2025.3.3b-x86_64
    - name: set up docker buildx
      uses: docker/setup-buildx-action@v3
    - name: create and push new manifest
      run: |
        docker buildx imagetools create \
          --annotation "index:org.opencontainers.image.source=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.source'] }}" \
          --annotation "index:org.opencontainers.image.description=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.description'] }}" \
          --annotation "index:org.opencontainers.image.licenses=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.licenses'] }}" \
          --annotation "index:org.opencontainers.image.authors=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.authors'] }}" \
          -t ghcr.io/${{ github.repository }}:test1 \
          ghcr.io/${{ github.repository }}:2025.3.3b-x86_64 \
          ghcr.io/${{ github.repository }}:2025.3.3b-aarch64
